# Generated by Django 5.1.7 on 2025-03-13 07:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='email_token',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='is_email_verified',
        ),
    ]
